version: "3"
services:
     website:
         image: php:apache
         depends_on:
          - api 
         environment:
           - USERNAME=toto
           - PASSWORD=python
         ports: 
          - 80:80
         volumes:
          - ./website:/var/www/html
     api:
         image: api
   
         volumes:
          - /home/centos/student-list/simple_api:/data
   

